---
application:
  name: "nfgw"
  project: "nwfg"
  organization: "QoveryCommunity"
  storage:
  - name: "disk"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/disk"
routers:
- name: "main-nfgw"
  routes:
  - application_name: "nfgw"
    paths:
    - "/*"
